// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentFeeManagement.Data;

#nullable disable

namespace StudentFeeManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250623154837_Fullfee")]
    partial class Fullfee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentFeeManagement.Model.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.AuditLogBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullBackupJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogBackups");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.DeleteRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentFeeId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeleteRequests");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.DeleteRequestBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullBackupJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeleteRequestBackups");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.EnrollmentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicGroupStudied")
                        .HasColumnType("text");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AdmissionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Admitted")
                        .HasColumnType("text");

                    b.Property<int>("ClassRollNo")
                        .HasColumnType("integer");

                    b.Property<string>("LanguagesGroupStudied")
                        .HasColumnType("text");

                    b.Property<string>("Marks")
                        .HasColumnType("text");

                    b.Property<string>("MediumOfInstruction")
                        .HasColumnType("text");

                    b.Property<string>("PreviousAcademicYear")
                        .HasColumnType("text");

                    b.Property<string>("PreviousAttendance")
                        .HasColumnType("text");

                    b.Property<string>("PreviousClass")
                        .HasColumnType("text");

                    b.Property<string>("StatusPreviousYear")
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectsGroupStudied")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentEnrollments");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.JobAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobAudits");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlternateMobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DisabilityPercentage")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HasDisabilityCertificate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsAAYBeneficiary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsBPLBeneficiary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsCWSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsEWS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsIndian")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsOutOfSchool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinorityGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotherTongue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOnAadhar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermanentEducationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SocialCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeOfImpairment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.StudentBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullBackupJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentBackups");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.StudentFee", b =>
                {
                    b.Property<int>("RegistrationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistrationNumber"));

                    b.Property<decimal?>("AdmissionAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AdmissionBillNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("AdmissionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BusFirstTermAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BusFirstTermFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusPoint")
                        .HasColumnType("text");

                    b.Property<decimal?>("BusSecondTermAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BusSecondTermFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClassSection")
                        .HasColumnType("text");

                    b.Property<decimal?>("Concession")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FirstTermAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstTermBillNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstTermDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FirstTermFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IsNewStudent")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<decimal?>("SecondTermAmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SecondTermBillNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SecondTermDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SecondTermFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RegistrationNumber");

                    b.ToTable("StudentFees");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.StudentFeeBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullBackupJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentFeeBackups");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.StudentFeeEditRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistrationNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("UpdatedAdmissionAmountPaid")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedAdmissionBillNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UpdatedAdmissionFee")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UpdatedBusFirstTermAmountPaid")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UpdatedBusFirstTermFee")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBusPoint")
                        .HasColumnType("text");

                    b.Property<decimal?>("UpdatedBusSecondTermAmountPaid")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UpdatedBusSecondTermFee")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedClassSection")
                        .HasColumnType("text");

                    b.Property<decimal?>("UpdatedConcession")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UpdatedFirstTermAmountPaid")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedFirstTermBillNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedFirstTermDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UpdatedFirstTermFee")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedIsNewStudent")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedRemarks")
                        .HasColumnType("text");

                    b.Property<decimal?>("UpdatedSecondTermAmountPaid")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedSecondTermBillNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedSecondTermDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UpdatedSecondTermFee")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedStudentName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedWhatsAppNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentFeeEditRequests");
                });

            modelBuilder.Entity("StudentFeeManagement.Model.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Educationinfamily")
                        .HasColumnType("text");

                    b.Property<string>("FacilitiesProvided")
                        .HasColumnType("text");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<string>("IsADHD")
                        .HasColumnType("text");

                    b.Property<string>("IsASD")
                        .HasColumnType("text");

                    b.Property<string>("IsCWSN")
                        .HasColumnType("text");

                    b.Property<string>("IsGifted")
                        .HasColumnType("text");

                    b.Property<string>("IsInNCC_NSS")
                        .HasColumnType("text");

                    b.Property<string>("IsInStateCompetition")
                        .HasColumnType("text");

                    b.Property<string>("IsInUseInternet")
                        .HasColumnType("text");

                    b.Property<string>("IsSLD")
                        .HasColumnType("text");

                    b.Property<string>("Residencetoschool")
                        .HasColumnType("text");

                    b.Property<string>("SLDType")
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentFeeManagement.Model.EnrollmentDetail", b =>
                {
                    b.HasOne("StudentFeeManagement.Model.Student", null)
                        .WithOne("Enrollment")
                        .HasForeignKey("StudentFeeManagement.Model.EnrollmentDetail", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentFeeManagement.Model.StudentProfile", b =>
                {
                    b.HasOne("StudentFeeManagement.Model.Student", null)
                        .WithOne("Profile")
                        .HasForeignKey("StudentFeeManagement.Model.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentFeeManagement.Model.Student", b =>
                {
                    b.Navigation("Enrollment")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
